site:
  name: Sonmyd
  site: 'https://sonmyd.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: Sonmyd - Soluciones Tecnológicas e IA
    template: '%s — Sonmyd'
  description: "\U0001F680 Transformamos tu negocio con IA, desarrollo web, apps multiplataforma y automatizaciones. Capacitaciones especializadas y soluciones tecnológicas de vanguardia."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Sonmyd
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@onwidget'
    site: '@onwidget'
    cardType: summary_large_image

i18n:
  language: es
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Ruta principal del blog, puedes cambiar esto a "articulos" (/articulos)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'categoria' # Ruta principal de categoría /categoria/alguna-categoria
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'etiqueta' # Ruta principal de etiqueta /etiqueta/alguna-etiqueta
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
